version: '3.1'
services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    container_name: a2-db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    container_name: adminer-a2

  model:
    build:
      context: ./db/
      dockerfile: dockerfile
    depends_on:
      - db

  app:
    build:
      context: ./backend/
    restart: always
    ports:
      - 3000:3000
    container_name: flask-app
    depends_on:
      - db
      
volumes:
  postgres-data:
