# Use the official Python image as the base image
FROM python

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install the required dependencies
RUN pip install -r requirements.txt

# Copy the application code into the container
COPY . .

# Expose the port that your Flask app will run on
EXPOSE 3000

# Define the command to run your Flask app
CMD ["python", "app.py"]
