# Use a imagem base do Python
FROM python:3.8

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie o arquivo requirements.txt para o contêiner
COPY requirements.txt requirements.txt

# Instale as dependências
RUN pip install -r requirements.txt

# Copie todos os arquivos do diretório atual para o contêiner
COPY . /app

# Exponha a porta em que o aplicativo Flask está sendo executado
EXPOSE 5000

# Comando para iniciar o aplicativo Flask
CMD ["python", "app.py"]
